# Generated by Django 4.0.2 on 2022-04-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hot_place',
            name='photo1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hot_place',
            name='photo2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hot_place',
            name='photo3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hot_place',
            name='photo4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hot_place',
            name='photo5',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
